Fix import error in Feast CLI (#314)
Due to this error:
AttributeError: module 'feast.loaders.file' has no attribute 'yaml_loader'

Since yaml_loader() function has been moved to a module feast.loaders.yaml